apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: badger-ken
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    name: webserver
